
// export const SET_ORDER = 'SET_ORDER';
// export const SET_ORDER_BY = 'SET_ORDER_BY';
// export const SELECT_ALL = 'SELECT_ALL';
// export const SELECT_ITEM = 'SELECT_ITEM';
// export const CHANGE_PAGE = 'CHANGE_PAGE';
// export const CHANGE_ROWS_PER_PAGE = 'CHANGE_ROWS_PER_PAGE';
// export const CHANGE_DENSE = 'CHANGE_DENSE';
// export const DELETE_SELECTED_DOCTORS_REQUEST = 'DELETE_SELECTED_DOCTORS_REQUEST';
// export const DELETE_SELECTED_DOCTORS_SUCCESS = 'DELETE_SELECTED_DOCTORS_SUCCESS';
// export const DELETE_SELECTED_DOCTORS_FAILURE = 'DELETE_SELECTED_DOCTORS_FAILURE';
